name: CI/CD

on: [push]

env:
  PYTHON_VERSION: 3.8

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: jebin90/pyaction:latest
        
    - name: Run Docker Container
      uses: docker://jebin90/pyaction:latest
      with:
        entrypoint: python
        args: ./main.py

